version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASSWORD=Neeraj@1234
      - DB_NAME=postgres
      - DB_PORT=5432
    depends_on:
      - database
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  database:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Neeraj@1234
      POSTGRES_DB: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

